### ISSUE TITLE
check design format

### ISSUE THREAD

**Issue by andronekomimi** [CharlesJB/metagene#55]
Hi,

There is no error thrown when I try to add an incorrect design file.

Here is the metagene object content :  
> names(mg$coverages)
[1] **"/home/nekomimi/Workspace/Imetagene/demo/align1_rep1.bam"** "/home/nekomimi/Workspace/Imetagene/demo/align1_rep2.bam"
[3] "/home/nekomimi/Workspace/Imetagene/demo/align2_rep1.bam" "/home/nekomimi/Workspace/Imetagene/demo/align2_rep2.bam"
[5] "/home/nekomimi/Workspace/Imetagene/demo/ctrl.bam"

Here is the design1
>  Samples | align1 | align2
1 **/home/nekomimi/Softs/R-3.2.1/library/metagene/extdata/Align1_rep1.bam** | 1 | 0
2 /home/nekomimi/Softs/R-3.2.1/library/metagene/extdata/align1_rep2.bam | 1 | 0
3 /home/nekomimi/Softs/R-3.2.1/library/metagene/extdata/align2_rep1.bam | 0 | 1
4 /home/nekomimi/Softs/R-3.2.1/library/metagene/extdata/align2_rep2.bam | 0 | 1
5        /home/nekomimi/Softs/R-3.2.1/library/metagene/extdata/ctrl.bam | 2 | 2

Well I try to add this design
> mg$add_design(design1) 

It works well and add the design to the metagene object.

Thank you

**Comment by CharlesJB** [comment]
The reason is that I want to allow user to use the same design with multiple `metagene` analysis (i.e.: to be able to use one large design object for multiple analysis). Thus, `metagene` only checks if the bam files are valid during the production of the matrices.

I will add a `check_bam_file` logical param to the add design function. If `TRUE`, the bam names will be checked and an error will be thrown if there is one or more bam files absent from the `metagene` object.
