### ISSUE TITLE
Parameter regions must not be an empty GRanges object

### ISSUE THREAD

**Issue by piotrsan** [CharlesJB/metagene#64]
Hi,

I am running metagene$new using as the region a GRange which is length(GR)>0.
However, I am getting this message:

Error in private$prepare_regions(regions, bam_file, force_seqlevels) : 
  Parameter regions must not be an empty GRanges object

any help would be much appreciated

**Comment by CharlesJB** [comment]
Hi piotrsan,

Could you give me the print result of the GRanges object you used and the complete `metagene$new` command you used.

I was not able to replicate the error you saw with the demo regions:
```r
> library(metagene)
> gr <- rtracklayer::import(get_demo_regions()[1])
> gr
GRanges object with 50 ranges and 0 metadata columns:
       seqnames                 ranges strand
          <Rle>              <IRanges>  <Rle>
   [1]     chr1   [16103663, 16105662]      *
   [2]     chr1   [23921318, 23923317]      *
   [3]     chr1   [34848977, 34850976]      *
   [4]     chr1   [36368182, 36370181]      *
   [5]     chr1   [36690488, 36692487]      *
   ...      ...                    ...    ...
  [46]     chr1 [172081530, 172083529]      *
  [47]     chr1 [172081796, 172083795]      *
  [48]     chr1 [172147016, 172149015]      *
  [49]     chr1 [172205805, 172207804]      *
  [50]     chr1 [172260642, 172262641]      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
> bam_files <- get_demo_bam_files()
> mg <- metagene$new(regions = gr, bam_files = bam_files)
> mg$get_regions()
GRangesList object of length 1:
$regions
GRanges object with 50 ranges and 0 metadata columns:
       seqnames                 ranges strand
          <Rle>              <IRanges>  <Rle>
   [1]     chr1   [16103663, 16105662]      *
[...]
```

**Comment by piotrsan** [comment]
Thanks CharlesJB

Here are the print results:
```{r}
> gr
GRanges object with 26183 ranges and 2 metadata columns:
          seqnames               ranges strand   |
             <Rle>            <IRanges>  <Rle>   |
      [1]    chr2L [16767954, 16768583]      +   |
      [2]    chr2L [16768884, 16769146]      +   |
      [3]    chr2L [16769290, 16770456]      +   |
      [4]    chr2L [16770837, 16770910]      +   |
      [5]    chr2L [16770974, 16771042]      +   |
      ...      ...                  ...    ... ...
  [26179]    chr2L [22960876, 22960931]      -   |
  [26180]    chr2L [22959815, 22959876]      -   |
  [26181]    chr2L [22959815, 22959876]      -   |
  [26182]    chr2L [22960833, 22960931]      -   |
  [26183]    chr2L [22961993, 22962623]      +   |
                                                id     score
                                       <character> <integer>
      [1] NM_001316398_intron_0_0_chr2L_16767955_f         0
      [2] NM_001316398_intron_1_0_chr2L_16768885_f         0
      [3] NM_001316398_intron_2_0_chr2L_16769291_f         0
      [4] NM_001316398_intron_3_0_chr2L_16770838_f         0
      [5] NM_001316398_intron_4_0_chr2L_16770975_f         0
      ...                                      ...       ...
  [26179] NM_001042961_intron_1_0_chr2L_22960877_r         0
  [26180] NM_001042959_intron_0_0_chr2L_22959816_r         0
  [26181] NM_001042960_intron_0_0_chr2L_22959816_r         0
  [26182] NM_001042960_intron_1_0_chr2L_22960834_r         0
  [26183]    NR_048041_intron_0_0_chr2L_22961994_f         0
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
> mg <- metagene$new(regions = gr, bam_files = bam_files, force = TRUE)
Error in private$prepare_regions(regions, bam_file, force_seqlevels) : 
  Parameter regions must not be an empty GRanges object
```
I used 
```{r}
force=TRUE
````
to bypass the following error
```{r}
> mg <- metagene$new(regions = gr, bam_files = bam_files)
Error in private$check_bam_levels(bam_file, regions, force = force_seqlevels) : 
  Some seqnames of regions are absent in bam_file
```
Thanks for helping out

**Comment by CharlesJB** [comment]
You have to make sure that all the seqlevels of the GRanges object are present in the bam file. For instance:

```r
> gr <- rtracklayer::import(get_demo_regions()[1])
> seqlevels(gr)
[1] "chr1"
> bam_file <- get_demo_bam_files()[1]
> seqlevels(Rsamtools::BamFile(bam_file))
 [1] "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18"
[10] "chr19" "chr1"  "chr2"  "chr3"  "chr4"  "chr5"  "chr6"  "chr7"  "chr8"
[19] "chr9"  "chrM"  "chrX"  "chrY"
> all(seqlevels(gr) %in% seqlevels(Rsamtools::BamFile(bam_file)))
[1] TRUE
> any(seqlevels(gr) %in% seqlevels(Rsamtools::BamFile(bam_file)))
[1] TRUE
```

The force argument will remove all the seqlevels in your GRanges that are not found in the bam file. It is useful for instance if you have alternative contigs in your GRanges but only the basic chromosomes in your bam file.

In your case, my impression is that your seqlevels use different chromosome representation in your GRanges and in your bam file. In this case, the force param will remove all the regions because it does not find any match in your bam files.

Can you use a command similar to the one in my example to see if the seqlevels in one of your bam files are the same as those in the GRanges (i.e.: is chr2 also represented as chr2L in the bam file)?

**Comment by piotrsan** [comment]
Thanks, that solved the issue.
Unfortunately I am now getting a different error in the next step. Do you have any document that describes the properties of the regions and bam_files necessary for the program to run successfully? 

This is the error:
```{r}
> mg$produce_matrices()
Error in intoNbins(gr, bcount) : all 'width(gr)' must be >= 'n'
```
My regions are of different sizes.

Thanks

**Comment by CharlesJB** [comment]
The bin_count param must be greater or equal than the smallest region in your GRange (`min(width(gr)`) because it's not possible to split a region in more bin than there are nucleotides.

An other option would be to resize your regions before calling `metagene$new`.

**Comment by piotrsan** [comment]
Resizing the regions worked, thanks.
I am now trying to push the data into a dataframe with no success.
I am doing the following:
```{r}
>mg$produce_data_frame(stat = "basic")
```
and get the following
```{r}
[1] "H_regions"
Error in private$check_param(data = data, ctrl = ctrl, alpha = alpha,  : 
  data must be a matrix with at least one value
```

any help would be appreciated. When I use get_matrices I do see a matrix that contains some numbers.

**Comment by CharlesJB** [comment]
Another user had the same problem recently. It was caused by regions located after the end of a chromosome. I currently have an issue (#63) about this and I plan to add more check to return an error early to avoid the error you saw.

Just to make sure it is the same problem, can you check if all your ranges in the GRanges object are within the length of each chromosome? Here is an example that shows what you should see if there are ranges outside a chromosome:

```r
> gr <- GRanges("chr10", IRanges(130694993, 130695993)) # Replace this part with your GRanges
> bam_file <- get_demo_bam_files()[1] # Replace this part with your bam file
> seqinfo(gr) <- seqinfo(Rsamtools::BamFile(bam_file))
Warning message:
In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 1 out-of-bound range located on sequence chr10.
  Note that only ranges located on a non-circular sequence whose length
  is not NA can be considered out-of-bound (use seqlengths() and
  isCircular() to get the lengths and circularity flags of the underlying
  sequences). You can use trim() to trim these ranges. See
  ?`trim,GenomicRanges-method` for more information.
```

If this is the cause of the error, it probably means that you used a different genome build for your alignments and for your GRanges.

If it's not the case, could you send me the metagene object by e-mail (you can use the one in the [metagene page on Bioconductor](https://bioconductor.org/packages/release/bioc/html/metagene.html)). I will investigate this to see what could be the cause. To save the metagene object:
```r
save(mg, file = "mg.RData")
```
